// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaKnp99POaptNDb3IFbPCLjd6sShxiwpQ',
    appId: '1:516909046519:android:cfe82fec4dd081fedb51f2',
    messagingSenderId: '516909046519',
    projectId: 'social-media-725a0',
    databaseURL: 'https://social-media-725a0-default-rtdb.firebaseio.com',
    storageBucket: 'social-media-725a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh9KkfSZPE1hp8ScXy-WGSQXjcf7EQrxE',
    appId: '1:516909046519:ios:f56d04495ebd5986db51f2',
    messagingSenderId: '516909046519',
    projectId: 'social-media-725a0',
    databaseURL: 'https://social-media-725a0-default-rtdb.firebaseio.com',
    storageBucket: 'social-media-725a0.firebasestorage.app',
    androidClientId: '516909046519-47r9o79og05m9gfnfbojl2rthh7e92s2.apps.googleusercontent.com',
    iosClientId: '516909046519-mvqn2l2l2o9s8s3s4omacuvric234t7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

}